exclude = [
  "target/**/*.toml",
  ".direnv/**/*.toml",
  "functional-tests/_dd/**/*.toml",
]

[formatting]
reorder_keys = false

[[rule]]
include = ["**/Cargo.toml"]
keys = ["workspace.dependencies", "dependencies"]

[rule.formatting]
reorder_keys = true
