[package]
name = "strata-paas"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
strata-prover-core.workspace = true
strata-service.workspace = true
strata-tasks.workspace = true

anyhow.workspace = true
serde.workspace = true
tokio = { workspace = true, features = ["sync", "time"] }
tracing.workspace = true
