//! Error types for the chain worker.

use strata_db_types::errors::DbError;
use strata_identifiers::{OLBlockCommitment, OLBlockId};
use strata_primitives::epoch::EpochCommitment;
use thiserror::Error;

/// Return type for worker messages.
pub type WorkerResult<T> = Result<T, WorkerError>;

/// Errors that can occur during chain worker operations.
#[derive(Debug, Error)]
pub enum WorkerError {
    /// Block not found in database.
    #[error("missing OL block {0}")]
    MissingOLBlock(OLBlockId),

    /// This usually means that we didn't execute the previous block.
    #[error("missing pre-state to execute block {0:?}")]
    MissingPreState(OLBlockCommitment),

    /// This might point to a database corruption or misused admin commands.
    /// The worker should not have tried to access block outputs that are missing.
    #[error("missing exec output for block {0:?}")]
    MissingBlockOutput(OLBlockCommitment),

    /// Missing write batch for a specific block, used for post-state reconstruction.
    #[error("missing write batch for block {0:?}")]
    MissingWriteBatch(OLBlockCommitment),

    /// This means that we haven't executed the block that's the terminal for an epoch.
    #[error("missing inner post-state of epoch {0} terminal {1:?}")]
    MissingEpochInnerPostState(u64, OLBlockCommitment),

    /// Missing epoch summary for the given commitment.
    #[error("missing summary for epoch commitment {0:?}")]
    MissingEpochSummary(EpochCommitment),

    /// Missing epoch summary for the given epoch munber.
    #[error("missing summary for at epoch {0:?}")]
    MissingEpochSummaryAt(u32),

    /// Generated by the worker handle when the worker has exited before being
    /// able to process a message we were trying to send.
    #[error("chain worker exited")]
    WorkerExited,

    /// STF execution error.
    #[error("STF execution failure: {0}")]
    StfExecution(#[from] strata_ol_stf::ExecError),

    /// Database error.
    #[error("database failure: {0}")]
    Database(#[from] DbError),

    /// Missing a required dependency for operation.
    #[error("missing required dependency: {0}")]
    MissingDependency(&'static str),

    /// Worker shutdown before genesis was processed.
    #[error("shutdown before genesis")]
    ShutdownBeforeGenesis,

    /// Genesis block not found at slot 0.
    #[error("genesis block not found at slot 0")]
    MissingGenesisBlock,

    /// Worker has not been initialized yet.
    #[error("worker not initialized")]
    NotInitialized,

    /// Generic unexpected error.
    #[error("unexpected failure: {0}")]
    Unexpected(String),

    /// Functionality not yet implemented.
    #[error("not yet implemented")]
    Unimplemented,
}
